export const ErrorCodes = {
  COUNTRY_CODES_NOT_FOUND: 'COUNTRY_CODES_NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  TOKEN_GENERATION_FAILED: 'TOKEN_GENERATION_FAILED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_EXIST: 'USER_ALREADY_EXIST',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  FILE_WRITE_TO_STORAGE_ERROR: 'FILE_WRITE_TO_STORAGE_ERROR',
} as const;
